### ISSUE TITLE
Weather Information Errors

### ISSUE THREAD

**Issue by Starstrike** [danielbrendel/hortusfox-web#190]
**Describe the bug**
Tried to use the new OpenWeatherMap functionality and I entered an API key I already had, but wouldn't get any results. I generated a new API key to enter and got what is shown in the screenshots.

First screenshot is with my API key I already had. The city is correct, just redacted.
Second screenshot is when I entered a new API key that I just generated.

**To Reproduce**
1. Go to openweathermap
2. Generate a new API key
3. Enter new API key on HortusFox
4. Get geolocation.
5. Save.
6. Go to Weather button at the top.

**Expected behavior**
What should happen is me seeing the weather forecast.

**Screenshots**
![image](https://github.com/danielbrendel/hortusfox-web/assets/1996734/9d0db6b3-92ab-4e40-90c7-cebc840f92cf)
![image](https://github.com/danielbrendel/hortusfox-web/assets/1996734/52bd7f82-4b0d-42f4-b8a9-f5868845a9ee)

**Software:**
- HortusFox version: 3.0
- PHP Version: 8.2.0
- MySQL version (if related to the problem): 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
- Docker version if used in a docker environment: 4.29 Docker Desktop for Windows
- Changes to your docker-compose file if altered

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 with WSL2 running Ubuntu
 - Browser [e.g. chrome, safari]: Edge
 - Version [e.g. 22]: 124

**Comment by danielbrendel** [comment]
Hi, thank you for your bug report. 

How long did you wait before using a new generated API key? For me it took about 2-3 hours for it to be activated.

What output do you get if you paste this in your browser?
```
http://api.openweathermap.org/data/2.5/forecast?appid=YOUR_NEW_API_KEY&lat=YOUR_LATITUDE&lon=YOUR_LONGITUDE&units=YOUR_UNIT_TYPE
```
Unit type can be _default_, _metric_ or _imperial_.

**Comment by Starstrike** [comment]
I just created a new one since I deleted the new one I had made. I'll wait for a couple hours to check it again. 

I did check with my existing key and it does show me results, but in HortusFox, all I get is what's in the first screenshot in my original post.

**Comment by Starstrike** [comment]
Ok, the new API is now populating info on that link you gave. The errors from the second screenshot are gone, but I'm still seeing what's in the first screenshot, no data.

**Comment by Starstrike** [comment]
In case it matters, when I first load up the site and I'm on the Dashboard, the weather does show there. So it seems like the issue is on the actual new weather page from the button at the top.

**Comment by danielbrendel** [comment]
I found out what's the issue and just published a fix. The problem is differing timezones. In some situations it can happen that your workspace uses a wrong timezone. I got this also when hosting workspaces for some of my friends. So now I published a fix that you can specify the timezone in the admin dashboard. There is a dropdown where you can choose from several timezones. 

It would be great if you could try the recent update (preferably in a testing environment).

**Comment by danielbrendel** [comment]
@Starstrike I'll close this issue for now due to it being resolved. If anything occurs nonetheless, feel free to post here so I can reopen the issue.

**Comment by Starstrike** [comment]
I don't see that 3.1 has been completed yet and that this was added to the milestone. I have watchtower looking for updates to this so as soon as 3.1 is available, I'll have it. Thanks for lookin' into this!

**Comment by kenske** [comment]
Still seeing this issue on 3.4. I checked the timezone setting in the admin dashboard and it's set to my correct timezone.

**Comment by dghoti** [comment]
I am still seeing this on HortusFox v3.7
PHP Version: 8.3.0
MySQL Version: 11.5.2-MariaDB-ubu2404
Server: Linux #1 SMP PREEMPT Debian 1:6.6.51-1+rpt1 (2024-09-26) on aarch64
Timezone: 2024-11-17 17:41 (Europe/Dublin)
is there a way to rest this without starting from scratch again? or do I justt backup then restore afer a fresh setup? Can I backup users too?
